a1_n10009671:
	gcc -c main.c -std=gnu99 -Wall -Werror -g -I../ZDK
	gcc -c gui.c -std=gnu99 -Wall -Werror -g -I../ZDK
	gcc main.o gui.o -std=gnu99 -Wall -Werror -g -I../ZDK -L../ZDK -lzdk -lncurses -lm -o a1_n10009671
